# Generated by Django 2.1.7 on 2019-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='player_1',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='team',
            name='player_2',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
